### ISSUE TITLE
Provide a method to broadcast messages from outside an actor

### ISSUE THREAD

**Issue by zacps** [Chris-Ricketts/actix-broker#5]
**Motivation:**
The vast majority of my actix-web application is implemented as actors, however there are some parts which are more convenient to implement as normal or async methods.

I want to be able to notify running actors of something that happened in a normal method, but there is no actor context.

**Workaround:**
Create a sentinel actor that sends the message (generic version untested):

```rust
struct Notifier<T>(T);

impl<T: Message> Actor for Notifier<T> {
    type Context = Context<Self>;

    fn started(&mut self, ctx: &mut Self::Context) {
        self.issue_system_async(self.0);
        ctx.stop();
    }
}
```

**Comment by zacps** [comment]
If you thought this was a good idea I'd be interested in implementing this, with a little guidance.

**Comment by chris-ricketts** [comment]
Hi @zacps,

Currently you can issue a message through the broker like so:
```rust 
#[derive(Clone, Message)]
struct Hello;
...
Broker::<SystemBroker>::issue_async(Hello);
```
This is used in the [actix-web example](https://github.com/chris-ricketts/actix-broker/blob/a3c511d2ad9abb1a662d6031c0c1ea4d17bef8ab/examples/actix-web.rs#L31).

Admittedly, this became less ergonomic since the broker was split between the system and local arbiters. 

Does this work for you? 

I would accept a pull request which adds two type aliases to the `broker` module so that `Broker::<SystemBroker>::issue_async(M);` can just become `SystemBroker::issue_async(M);` and likewise for `ArbiterBroker`.

In which case the current `SystemBroker` and `ArbiterBroker` types would need renamed.

**Comment by zacps** [comment]
To be honest I don't think the type aliases are necessary, they can always be added by the user if they think they're necessary.

Do you think it would be a good idea to change or add an example in the documentation? I completely missed the examples because they weren't linked from the readme/docs.rs page.
